[package]
cairo-version = "=2.12.1"
name = "budokan"
version = "0.0.1"
edition = "2024_07"

[lib]

[[target.starknet-contract]]
sierra = true
casm = true
build-external-contracts = [
    "dojo::world::world_contract::world",
    "game_components_test_starknet::minigame::mocks::minigame_starknet_mock::minigame_starknet_mock",
    "game_components_test_starknet::metagame::mocks::metagame_starknet_mock::metagame_starknet_mock",
    "game_components_token::examples::full_token_contract::FullTokenContract",
    "game_components_token::examples::minigame_registry_contract::MinigameRegistryContract",
]

[dependencies]
openzeppelin_introspection = "2.0.0"
openzeppelin_token = "2.0.0"
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.7.0-alpha.2" }
dojo_macros = { git = "https://github.com/dojoengine/dojo", tag = "v1.7.0-alpha.2" }
game_components_metagame = { git = "https://github.com/credence0x/game-components"}
game_components_minigame = { git = "https://github.com/credence0x/game-components" }
game_components_utils = { git = "https://github.com/credence0x/game-components" }
game_components_test_starknet = { git = "https://github.com/credence0x/game-components" }
game_components_token = { git = "https://github.com/credence0x/game-components" }
starknet = "2.12.1"

[dev-dependencies]
dojo_cairo_test = { git = "https://github.com/dojoengine/dojo.git", tag = "v1.7.0-alpha.2" }
cairo_test = "2.12.1"

[features]
default = []

[profile.dev]
[profile.slot]
[profile.sepolia]
[profile.mainnet]